image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: pipenv --python /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/python3.8
  command: pipenv install --dev
- init: mkdir -p /workspace/data
  command: mongod --dbpath /workspace/data

vscode:
  extensions:
    - almenon.arepl@1.0.20:Uu7lIOwyLgmNWpTwCl/iqQ==
