image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8000
  onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: PIP_USER=no poetry install --no-root
- init: mkdir -p /workspace/data
  command: mongod --dbpath /workspace/data --bind_ip 127.0.0.1

vscode:
  extensions:
    - DavidAnson.vscode-markdownlint@0.36.1:qV04OEElMWIf9PHKK19GYA==
    - mongodb.mongodb-vscode@0.1.1:YxL4c1szW0z9jpy6o32YLg==