language: python
python: 
- 'pypy3.6-7.3.1'
services:
- docker
env:
  DOCKER_REPOSITORY=jlaasonen/ebl-api
install:
- pipenv install --dev
- yes | pip uninstall numpy
jobs:
  include:
    - stage: test
      script: pipenv run black ebl --check
      name: "Code Style"
    - 
      script: pipenv run flake8
      name: "Lint"
    -
      script: pipenv run pyre --typeshed "${VIRTUAL_ENV}/lib/pyre_check/typeshed" check
      name: "Type Check"
    -
      before_script:
        - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
        - chmod +x ./cc-test-reporter
        - "./cc-test-reporter before-build"
      script: pipenv run pytest --cov=ebl --cov-report term --cov-report xml
      after_script: "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
      name: "Unit Tests"
    - stage: docker
      if: branch = master AND type != pull_request
      install: skip
      script:
        - docker build -t "$DOCKER_REPOSITORY:$TRAVIS_BRANCH" -t "$DOCKER_REPOSITORY:$TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER" .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_REPOSITORY
notifications:
  slack:
    secure: Uta5GfEtMLHux2hEuLrDFk0FrZdpkO68JplQ20SdnKvLmPs4hjGhDtw89WHGcPVzCK3wolzZyg3vk0YthMQU8naiTxZ3O2pi39ff3jTY7IDx1UzNT7EH2d/72fl8uIGHciGvZteIKmNnyaRdTpl1zFtvUWFLJqZm5cONtJ7rQdsMGGUygcwHVR6GNbKQnZY8oLNHYjV3oe3PfRZnqbzRTIbqXyz9TeW832fi58EyUUl31ERvMOltZTxKOGIazqEmn6Ei1sRygqL0VC2V5sDZDuM1ih+sTxwUL3vUQPEp22lhNigOTCy8ZGALGfXgO/5ziiAmQ4XbIzxsWuLF3x2QqrUKNpiEnbn/6HPJPvfdwiW4SKqYWlHrESyL1UTtzwUBnoIrQpGLKlss4a7ZW43CybBm7VbpSKmRGdcZ9Dw3VoGcJ+gQ4AQ/UEyxg+vQZT2zwVycYNpDulhTAe1omj95K+YulmMQiomsA9w7DADDJ09eOR0sCXCvonYAXKvKmQHXNIL+zTVwdiqs/c61ZXghPAawoW9LlR8O8f6EPRF2v+qE5YrRq4tOaUqcCT3NuUIfkPYxw6W3oN6rYVOwLogyvy7piT2DRyU8IzsuniFRQzec34ij6oHHbjFE/BK+u7woaVU3o2SP0Eq0I242FIzICONN8gnWucPzzBBiRWhRhHQ=
