version: '3'
services:
  api:
    build: .
    ports:
      - 8000:8000
    links:
      - mongo
    environment:
      - AUTH0_AUDIENCE
      - AUTH0_ISSUER
      - AUTH0_PEM
      - MONGODB_URI=mongodb://mongo:27017/ebl
      - NEW_RELIC_LICENSE_KEY
      - NEW_RELIC_CONFIG_FILE
      - SENTRY_DSN
      - SENTRY_ENVIRONMENT
    volumes:
      - ./ebl:/usr/src/ebl/ebl
    command:  ["pipenv", "run", "gunicorn",  "--reload", "-b :8000", "ebl.app:get_app()"]
    restart: always
  mongo:
    # If ports are opened the DB must use authentication.
    image: mongo
    restart: always
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
