version: '3'
services:
  api:
    build: .
    ports:
    - "8000:8000"
    links:
    - mongo
    environment:
      - AUTH0_AUDIENCE
      - AUTH0_ISSUER
      - AUTH0_PEM
      - MONGODB_URI
  mongo:
    image: mongo
