name: CI

on:
  push:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PIPENV_VENV_IN_PROJECT: 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 'pypy3'

      - name: Install
        id: install
        run: |
          pip install pipenv
          pipenv install --dev --deploy

      - name: Lint
        if: success() || steps.install.outcome == 'success'
        run: pipenv run lint
      
      - name: Code Style
        if: success() || steps.install.outcome == 'success'
        run: pipenv run black ebl --check

      - name: Type Check
        if: success() || steps.install.outcome == 'success'
        run: pipenv run pyre check

      - name: Unit Tests
        id: unit_tests
        env:
          CI: true
        run: pipenv run test
          
      - uses: paambaati/codeclimate-action@v2.7.4
        if: success() || steps.unit_tests.outcome == 'failure'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          
  docker:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v1
        
      - uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            jlaasonen/ebl-api:latest
            ${{format('jlaasonen/ebl-api:master.{0}', github.run_number)}}
